### PR TITLE
use arc_token() to handle empty tokens

### PR DESCRIPTION
**Pull request by kbvernon**
## Checklist 

- [x] update NEWS.md
- [x] documentation updated with `devtools::document()`
- [x] `devtools::check()` passes locally

## Changes 

When "ARCGIS_TOKEN" is an empty string, it will sometimes cause HTTP 498 "invalid token" error. Need to NULL the empty string to handle this. 

**Issues that this closes** 

No issue opened here. See https://github.com/R-ArcGIS/arcgisutils/issues/5.

## Follow up tasks

Waiting for https://github.com/R-ArcGIS/arcgisutils/pull/6 to be merged first.

### CODE REVIEW

**Comment by kbvernon** [comment]
May have jumped the gun not running `devtools::document()` first. Hopefully, that doesn't cause any issues. `devtools::check()` is going to break until the `{arcgisutils}` PR gets merged.

**Comment by JosiahParry** [comment]
We need to bump the minimum version of `arcgisutils` to `0.1.1.9000` to ensure compatibility. Can you change the minimum version? That should also get CI to download the correct version of arcgisutils.

**Comment by kbvernon** [comment]
Can do, but is there a programmatic way to do that, maybe with `{usethis}`, or do I just go in and edit the DESCRIPTION by hand?

**Comment by JosiahParry** [comment]
@kbvernon can you remove this portion here? It's causing R CMD Check to fail because it was single handedly handling this bug. But now it should be working without this conditional.
https://github.com/R-ArcGIS/arcgislayers/blob/203bbbca74fba2f5085709f433f22819d75feb2d/R/get-estimates.R#L39-L51

**Comment by kbvernon** [comment]
ha, it appears this issue has come up before...

**Comment by kbvernon** [comment]
it appears i chopped out that code uncritically, let me replace it with what needs to go there

**Comment by kbvernon** [comment]
`devtools::check()` just ran without error on my local machine, hopefully it passes here, too

**Comment by JosiahParry** [comment]
We'll make a package dev of you yet!

**Pull request merged**
